name: build-preview
run-name: build pull request preview

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        if: runner.debug == '1'
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install Ruby packages
        if: github.event.action != 'closed'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Setup Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run site health checks
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement tools/requirements-site-check.txt
          python tools/site_health_check.py

      - name: Get Pages url
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@v4

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Build preview version of site
        if: github.event.action != 'closed'
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"

      - name: Commit preview to Pages branch
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}

      - name: Checkout Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Clean up preview folders
        uses: actions/github-script@v7
        with:
          script: |
            const { rm } = require("fs").promises;
            const { PREVIEWS_FOLDER } = process.env;
            const { owner, repo } = context.repo;
            const prs = (await github.rest.pulls.list({ owner, repo, state: "closed" })).data;
            for (const { number } of prs)
              await rm(`${PREVIEWS_FOLDER}/pr-${number}`, { recursive: true, force: true });

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "Clean up previews"
